// packages/react/src/components/MoneyFill.tsx
import React from 'react';

export interface MoneyFillProps {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  'aria-label'?: string;
  title?: string;
}

export const MoneyFill: React.FC<MoneyFillProps> = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
  'aria-label': ariaLabel,
  title,
}) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
      aria-label={ariaLabel}
      role={title ? 'img' : undefined}
    >
      {title && <title>{title}</title>}
      <path d="M12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22C17.5 22 22 17.5 22 12C22 6.5 17.5 2 12 2ZM16 11.6V12.6H12.7V14.4H16V15.4H12.7V18H11.4V15.4H8V14.4H11.3V12.6H8V11.6H10.6L7.8 7H9.3L12 11.4L14.7 7H16.2L13.4 11.6H16Z" fill={color} />
    </svg>
  );
};

MoneyFill.displayName = 'MoneyFill';

// packages/svelte/src/components/MoneyFill.svelte
<script lang="ts">
  export let size: number | string = 24;
  export let color: string = 'currentColor';
  let className: string = '';
  export { className as class };
  export let style: string = '';
  export let title: string | undefined = undefined;

  $: svgStyle = `vertical-align: middle;${style ? ' ' + style : ''}`;
  $: ariaLabel = $$props['aria-label'] as string | undefined;
  $: role = title ? 'img' : undefined;
</script>

<svg
  width={size}
  height={size}
  viewBox="0 0 24 24"
  fill="none"
  xmlns="http://www.w3.org/2000/svg"
  class={className}
  style={svgStyle}
  aria-label={ariaLabel}
  {role}
>
  {#if title}
    <title>{title}</title>
  {/if}
  <path d="M12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22C17.5 22 22 17.5 22 12C22 6.5 17.5 2 12 2ZM16 11.6V12.6H12.7V14.4H16V15.4H12.7V18H11.4V15.4H8V14.4H11.3V12.6H8V11.6H10.6L7.8 7H9.3L12 11.4L14.7 7H16.2L13.4 11.6H16Z" fill={color} />
</svg>
