// packages/vue/src/components/LuggageFill.vue
<script setup lang="ts">
import { computed, type StyleValue } from 'vue';

export interface LuggageFillProps {
  size?: number | string;
  color?: string;
  class?: string;
  style?: StyleValue;
  'aria-label'?: string;
  title?: string;
}

const props = withDefaults(defineProps<LuggageFillProps>(), {
  size: 24,
  color: 'currentColor',
});

const svgStyle = computed(() => {
  const baseStyle: StyleValue = { verticalAlign: 'middle' };
  if (props.style) {
    if (typeof props.style === 'string') {
      return baseStyle;
    }
    return { ...baseStyle, ...props.style };
  }
  return baseStyle;
});

const svgAttrs = computed(() => {
  const attrs: Record<string, any> = {};
  if (props['aria-label']) {
    attrs['aria-label'] = props['aria-label'];
  }
  if (props.title) {
    attrs.role = 'img';
  }
  return attrs;
});
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    :class="props.class"
    :style="svgStyle"
    v-bind="svgAttrs"
  >
    <title v-if="title">{{ title }}</title>
    <path d="M15 2H9V5H5V20H7.6C7.5 20.2 7.5 20.3 7.5 20.5C7.5 21.3 8.2 22 9 22C9.8 22 10.5 21.3 10.5 20.5C10.5 20.3 10.5 20.2 10.4 20H13.6C13.5 20.2 13.5 20.3 13.5 20.5C13.5 21.3 14.2 22 15 22C15.8 22 16.5 21.3 16.5 20.5C16.5 20.3 16.5 20.2 16.4 20H19V5H15V2ZM9.5 16.5H8.5V9H9.5V16.5ZM12.5 16.5H11.5V9H12.5V16.5ZM13.5 5H10.5V3.5H13.5V5ZM15.5 9V16.5H14.5V9H15.5Z" :fill="color" />
  </svg>
</template>

// packages/react/src/components/LuggageFill.tsx
import React from 'react';

export interface LuggageFillProps {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  'aria-label'?: string;
  title?: string;
}

export const LuggageFill: React.FC<LuggageFillProps> = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
  'aria-label': ariaLabel,
  title,
}) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
      aria-label={ariaLabel}
      role={title ? 'img' : undefined}
    >
      {title && <title>{title}</title>}
      <path d="M15 2H9V5H5V20H7.6C7.5 20.2 7.5 20.3 7.5 20.5C7.5 21.3 8.2 22 9 22C9.8 22 10.5 21.3 10.5 20.5C10.5 20.3 10.5 20.2 10.4 20H13.6C13.5 20.2 13.5 20.3 13.5 20.5C13.5 21.3 14.2 22 15 22C15.8 22 16.5 21.3 16.5 20.5C16.5 20.3 16.5 20.2 16.4 20H19V5H15V2ZM9.5 16.5H8.5V9H9.5V16.5ZM12.5 16.5H11.5V9H12.5V16.5ZM13.5 5H10.5V3.5H13.5V5ZM15.5 9V16.5H14.5V9H15.5Z" fill={color} />
    </svg>
  );
};

LuggageFill.displayName = 'LuggageFill';
