// packages/vue/src/components/StampLine.vue
<script setup lang="ts">
import { computed, type StyleValue } from 'vue';

export interface StampLineProps {
  size?: number | string;
  color?: string;
  class?: string;
  style?: StyleValue;
  'aria-label'?: string;
  title?: string;
}

const props = withDefaults(defineProps<StampLineProps>(), {
  size: 24,
  color: 'currentColor',
});

const svgStyle = computed(() => {
  const baseStyle: StyleValue = { verticalAlign: 'middle' };
  if (props.style) {
    if (typeof props.style === 'string') {
      return baseStyle;
    }
    return { ...baseStyle, ...props.style };
  }
  return baseStyle;
});

const svgAttrs = computed(() => {
  const attrs: Record<string, any> = {};
  if (props['aria-label']) {
    attrs['aria-label'] = props['aria-label'];
  }
  if (props.title) {
    attrs.role = 'img';
  }
  return attrs;
});
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    :class="props.class"
    :style="svgStyle"
    v-bind="svgAttrs"
  >
    <title v-if="title">{{ title }}</title>
    <path d="M18 12C19.1 12 20 12.9 20 14V18.5H4V14C4 12.9 4.9 12 6 12H9.6L8.3 7.3C7.7 4.9 9.5 2.5 12 2.5C14.5 2.5 16.4 4.9 15.7 7.3L14.4 12H18ZM10.2 4.9C9.8 5.5 9.6 6.2 9.8 6.9L11.2 12H12.9L14.2 6.9C14.4 6.2 14.2 5.5 13.8 4.9C13.4 4.3 12.7 4 12 4C11.3 4 10.6 4.3 10.2 4.9ZM18.5 14C18.5 13.7 18.3 13.5 18 13.5H6C5.7 13.5 5.5 13.7 5.5 14V17H18.5V14ZM2.5 22V20.5H21.5V22H2.5Z" :fill="color" />
  </svg>
</template>

// packages/react/src/components/StampLine.tsx
import React from 'react';

export interface StampLineProps {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  'aria-label'?: string;
  title?: string;
}

export const StampLine: React.FC<StampLineProps> = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
  'aria-label': ariaLabel,
  title,
}) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
      aria-label={ariaLabel}
      role={title ? 'img' : undefined}
    >
      {title && <title>{title}</title>}
      <path d="M18 12C19.1 12 20 12.9 20 14V18.5H4V14C4 12.9 4.9 12 6 12H9.6L8.3 7.3C7.7 4.9 9.5 2.5 12 2.5C14.5 2.5 16.4 4.9 15.7 7.3L14.4 12H18ZM10.2 4.9C9.8 5.5 9.6 6.2 9.8 6.9L11.2 12H12.9L14.2 6.9C14.4 6.2 14.2 5.5 13.8 4.9C13.4 4.3 12.7 4 12 4C11.3 4 10.6 4.3 10.2 4.9ZM18.5 14C18.5 13.7 18.3 13.5 18 13.5H6C5.7 13.5 5.5 13.7 5.5 14V17H18.5V14ZM2.5 22V20.5H21.5V22H2.5Z" fill={color} />
    </svg>
  );
};

StampLine.displayName = 'StampLine';
