// packages/react/src/components/BankAccountLine.tsx
import React from 'react';

export interface BankAccountLineProps {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  'aria-label'?: string;
  title?: string;
}

export const BankAccountLine: React.FC<BankAccountLineProps> = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
  'aria-label': ariaLabel,
  title,
}) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
      aria-label={ariaLabel}
      role={title ? 'img' : undefined}
    >
      {title && <title>{title}</title>}
      <path d="M2 17.2V4H22V17.2C22 18.8 20.7 20 19.2 20H4.7C3.2 20 2 18.8 2 17.2ZM20.5 7V5.5H3.5V7H20.5ZM4.7 18.5H19.2C19.9 18.5 20.5 17.9 20.5 17.3V8.5H3.5V17.3C3.5 17.9 4 18.5 4.7 18.5ZM11.9992 12.4L13.5992 9.5H14.7992L13.0992 12.5H14.4992V13.5H12.4992V14.5H14.4992V15.5H12.4992V17H11.4992V15.5H9.49922V14.5H11.4992V13.5H9.49922V12.5H10.8992L9.19922 9.5H10.3992L11.9992 12.4Z" fill={color} />
    </svg>
  );
};

BankAccountLine.displayName = 'BankAccountLine';

// packages/vue/src/components/BankAccountLine.vue
<script setup lang="ts">
import { computed, type StyleValue } from 'vue';

export interface BankAccountLineProps {
  size?: number | string;
  color?: string;
  class?: string;
  style?: StyleValue;
  'aria-label'?: string;
  title?: string;
}

const props = withDefaults(defineProps<BankAccountLineProps>(), {
  size: 24,
  color: 'currentColor',
});

const svgStyle = computed(() => {
  const baseStyle: StyleValue = { verticalAlign: 'middle' };
  if (props.style) {
    if (typeof props.style === 'string') {
      return baseStyle;
    }
    return { ...baseStyle, ...props.style };
  }
  return baseStyle;
});

const svgAttrs = computed(() => {
  const attrs: Record<string, any> = {};
  if (props['aria-label']) {
    attrs['aria-label'] = props['aria-label'];
  }
  if (props.title) {
    attrs.role = 'img';
  }
  return attrs;
});
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    :class="props.class"
    :style="svgStyle"
    v-bind="svgAttrs"
  >
    <title v-if="title">{{ title }}</title>
    <path d="M2 17.2V4H22V17.2C22 18.8 20.7 20 19.2 20H4.7C3.2 20 2 18.8 2 17.2ZM20.5 7V5.5H3.5V7H20.5ZM4.7 18.5H19.2C19.9 18.5 20.5 17.9 20.5 17.3V8.5H3.5V17.3C3.5 17.9 4 18.5 4.7 18.5ZM11.9992 12.4L13.5992 9.5H14.7992L13.0992 12.5H14.4992V13.5H12.4992V14.5H14.4992V15.5H12.4992V17H11.4992V15.5H9.49922V14.5H11.4992V13.5H9.49922V12.5H10.8992L9.19922 9.5H10.3992L11.9992 12.4Z" :fill="color" />
  </svg>
</template>
