// packages/react/src/components/HealthLine.tsx
import React from 'react';

export interface HealthLineProps {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  'aria-label'?: string;
  title?: string;
}

export const HealthLine: React.FC<HealthLineProps> = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
  'aria-label': ariaLabel,
  title,
}) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
      aria-label={ariaLabel}
      role={title ? 'img' : undefined}
    >
      {title && <title>{title}</title>}
      <path d="M16 2C14.5 2 13.1 2.6 12 3.6C10.9 2.6 9.5 2 8 2C4.7 2 2 4.7 2 8C2 15.7 11.2 21.5 11.6 21.8L12 22L12.4 21.8C12.8 21.6 22 15.8 22 8C22 4.7 19.3 2 16 2ZM12 20.2C10.3 19 3.5 14 3.5 8C3.5 5.5 5.5 3.5 8 3.5C9.3 3.5 10.6 4.1 11.4 5.1L12 5.8L12.6 5.1C13.5 4.1 14.7 3.5 16 3.5C18.5 3.5 20.5 5.5 20.5 8C20.5 14 13.7 19 12 20.2Z" fill={color} />
    </svg>
  );
};

HealthLine.displayName = 'HealthLine';

// packages/vue/src/components/HealthLine.vue
<script setup lang="ts">
import { computed, type StyleValue } from 'vue';

export interface HealthLineProps {
  size?: number | string;
  color?: string;
  class?: string;
  style?: StyleValue;
  'aria-label'?: string;
  title?: string;
}

const props = withDefaults(defineProps<HealthLineProps>(), {
  size: 24,
  color: 'currentColor',
});

const svgStyle = computed(() => {
  const baseStyle: StyleValue = { verticalAlign: 'middle' };
  if (props.style) {
    if (typeof props.style === 'string') {
      return baseStyle;
    }
    return { ...baseStyle, ...props.style };
  }
  return baseStyle;
});

const svgAttrs = computed(() => {
  const attrs: Record<string, any> = {};
  if (props['aria-label']) {
    attrs['aria-label'] = props['aria-label'];
  }
  if (props.title) {
    attrs.role = 'img';
  }
  return attrs;
});
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    :class="props.class"
    :style="svgStyle"
    v-bind="svgAttrs"
  >
    <title v-if="title">{{ title }}</title>
    <path d="M16 2C14.5 2 13.1 2.6 12 3.6C10.9 2.6 9.5 2 8 2C4.7 2 2 4.7 2 8C2 15.7 11.2 21.5 11.6 21.8L12 22L12.4 21.8C12.8 21.6 22 15.8 22 8C22 4.7 19.3 2 16 2ZM12 20.2C10.3 19 3.5 14 3.5 8C3.5 5.5 5.5 3.5 8 3.5C9.3 3.5 10.6 4.1 11.4 5.1L12 5.8L12.6 5.1C13.5 4.1 14.7 3.5 16 3.5C18.5 3.5 20.5 5.5 20.5 8C20.5 14 13.7 19 12 20.2Z" :fill="color" />
  </svg>
</template>
